name: Python

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install -r python/requirements.txt
    - name: Check style compliance
      run: |
        pycodestyle --show-source --show-pep8 --ignore=E501 --verbose .
      working-directory: ./python
